### PR TITLE
82 backend tests for api

### PR DESCRIPTION
**Pull request by rorychatt**

### CODE REVIEW

**Comment by rorychatt** [comment]
@Oshulten sorry, what happened here?

**Comment by Oshulten** [comment]
> @Oshulten sorry, what happened here?

I'm sorry, I thought you intended us to review and then merge the PR into main? Were you still active on that branch?

**Comment by rorychatt** [comment]
@Oshulten ill just start a new one, no worries, but pls don't merge and delete other's branches :D

**Comment by Oshulten** [comment]
Sorry, seems like I'm not entirely clear on how people use PRs yet. I restored the branch if that helps

**Pull request merged**
