### PR TITLE
60 backend handle transactions

### PR DESCRIPTION
**Pull request by rorychatt**
image

### CODE REVIEW

**Comment by rorychatt** [comment]
just a casual 1k lines of code nothing to see here

**Comment by rorychatt** [comment]
this requires testing too btw

**Review by timabloom — COMMENTED** [review]
Only odd thing is that they are all get Get HTTP requests but they all return only a status code with a message

**Comment by rorychatt** [comment]
> Only odd thing is that they are all get Get endpoints but all responses returns just a status code with a message

Hmmm, I guess later on we will want to actually get something from these endpoints

**Comment by timabloom** [comment]
I think it might be better to change them to Put, Patch or Post and send the id's in a body. The requests are adding and editing data in the database not retrieving data from it

**Pull request merged**
